### ISSUE TITLE
Use also key opening_hours:covid19

### ISSUE THREAD

**Issue by sfkeller** [Qwant/qwantmaps#111]
During these weeks of lockdown it's perhaps very useful to parse also key opening_hours:covid19 for showing opening hours - as already suggested here https://twitter.com/sfkeller/status/1245838357135065099 .

The docs about key opening_hours:covid19 are here https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19 and there's following web app which displays it already - but only for France: "Ça reste ouvert" https://www.caresteouvert.fr/ (repo: https://github.com/osmontrouge/caresteouvert ).

**Comment by amatissart** [comment]
We are already using these tags `opening_hours:covid19` and `description:covid19` for points of interest located in France, [with a direct link ](https://github.com/QwantResearch/erdapfel/pull/588 )to caresteouvert.fr in order to promote contribution to the project.

There would be little technical difficulty to use these tags in other countries. But displaying relevant information, in compliance with local legislation and recommendations is more challenging.  
We will do our best.

**Comment by FozzieHi** [comment]
@amatissart Any update on this? I don't see how it'd violate local legislation in other countries.
