### ISSUE TITLE
No crawling of the data outside of big cities ?

### ISSUE THREAD

**Issue by Kalytis** [Qwant/qwantmaps#120]
Hello,

Whenever I add something in OpenStreetMap in big cities (like Nantes), it's added within 48 hours. But I just noticed that a modification I made 6 months ago in the countryside (Marcillac-Saint-Quentin, 24200) still isn't added to Qwant Maps.

Is there a problem with the update of data outside of big cities ?

**Comment by amatissart** [comment]
Thanks for your feedback!

The update of OpenStreetMap data is based on diff files published on https://planet.openstreetmap.org/ that cover the entire planet. So it seems very unlikely that a specific location would be left behind.

The change you are referring to more probably relates to a kind of item that is not currently included on Qwant Maps.
Some users already brought to our attention (see #83) that they would like more diverse items to appear on the map.
And that's why we plan to extend how the different Points of Interest are extracted from OSM data, to cover most of these cases.
