### ISSUE TITLE
OpenStreetMap is updated but qwantmaps still shows wrong information

### ISSUE THREAD

**Issue by PackElend** [Qwant/qwantmaps#155]
https://www.qwant.com/maps/place/latlon:47.49926:-2.77727#map=19.66/47.4991651/-2.7769973
shows the same road name as shown on the map.

I updated OSM, see here:
https://www.openstreetmap.org/node/5898430670

**Comment by amatissart** [comment]
Thanks for your feedback.  

The map itself and most of the details about points of interest are updated on a daily basis.
However, the addresses database is updated less frequently and follows a different and more convoluted process to integrate data from different sources. 

For addresses located in France, Qwant Maps relies on [BANO](https://bano.openstreetmap.fr/) that also aggregates data from official datasets in addition to OSM. In your specific example, the aggregation didn't work at first, because the street name was known in other sources as "Allée des Hauts de Roc'h Braz". Adding the tag `ref:FR:FANTOIR` on [the street relation](https://www.openstreetmap.org/relation/13024756) fixed the aggregation.  

For more details about contributing to BANO, see https://wiki.openstreetmap.org/wiki/Contribuer_%C3%A0_la_BANO

Now that the new address is correctly listed in BANO, it should appear on Qwant Maps soon.

**Comment by PackElend** [comment]
thx for doing the fix :)

It is even correct https://ign.fr / [geoportail.gouv.fr](https://www.geoportail.gouv.fr/carte?c=-2.7774537738841,47.49921077397286&z=20&l0=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN-EXPRESS.STANDARD::GEOPORTAIL:OGC:WMTS(1)&l1=GEOGRAPHICALGRIDSYSTEMS.MAPS.BDUNI.J1::GEOPORTAIL:OGC:WMTS(1)&permalink=yes) on ign
but 
![image](https://user-images.githubusercontent.com/3542031/127838905-0eacf3f7-9c70-4e43-ad07-37e803b7e9c0.png)
was done a couple of days ago
may that fixes the information pulled from BANO 

----

> However, the addresses database is updated less frequently and follows a different and more convoluted process to integrate data from different sources.

how often does this happen?

----

you added 
<html>
<body>


ref:FR:FANTOIR | 562401203G
-- | --



</body>
</html>
where does the number come from?
I see it on http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/47.49937/-2.77766 but no clue what it means

![image](https://user-images.githubusercontent.com/3542031/127840649-22146eb8-ec23-418d-8973-ddc4b8a1fc40.png)

**Comment by amatissart** [comment]
> > However, the addresses database is updated less frequently and follows a different and more convoluted process to integrate data from different sources.
> 
> how often does this happen?

Typically once a month. But we noticed some quality issues about postal codes in some sources lately, so the data currently visible on production is older. We are working on making this process more robust, and performing quality checks. The addresses should be updated in a few weeks at the latest.


> you added
> ref:FR:FANTOIR 	562401203G
> where does the number come from? I see it on http://tile.openstreetmap.fr/~cquest/leaflet/bano.html#18/47.49937/-2.77766 but no clue what it means
> 
> ![image](https://user-images.githubusercontent.com/3542031/127840649-22146eb8-ec23-418d-8973-ddc4b8a1fc40.png)

This is a code from the "FANTOIR" database, used as a reference for street names in France.
see https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:FANTOIR  
The raw dataset is [available on data.gouv.fr](https://www.data.gouv.fr/fr/datasets/fichier-fantoir-des-voies-et-lieux-dits/). 

A slightly more convenient way to find this code is to use the tools provided by BANO to compare this reference with OSM data:
http://bano.openstreetmap.fr/fantoir/index.html#insee=56240&tab=1

**Comment by PackElend** [comment]
> The raw dataset is [available on data.gouv.fr](https://www.data.gouv.fr/fr/datasets/fichier-fantoir-des-voies-et-lieux-dits/).

that is hopefully updated soon due to contacting https://ign.fr / geoportail.gouv.fr
