### ISSUE TITLE
Search by type instead of name

### ISSUE THREAD

**Issue by yotamN** [Qwant/qwantmaps#90]
In addition to the eight categories that are shown it would be nice to be able to search for more categories and be able to contribute such categories.  
For example I might want to search for an ATM in general and not an ATM with a name.

**Comment by i-need-to-tell-you-something** [comment]
I agree.

There is a nice selection of features users can search for right now. But I think there is a lot more data in OSM that could in theory be leveraged and made accessible to users. It is difficult to foresee what some users will desperately need. Some examples:

- `emergency=defibrillator`
- `amenity=fire_station`
- `amenity=food_sharing`
- `leisure=playground`
- `amenity=bicycle_parking`
- `amenity=drinking_water`
- `amenity=post_box`

The engine to use for translating user searched strings into meaningful OSM data types (tags and keys) - which among others returns `zoo` and `veterinary clinic` when queried for `animal` - could be the same one that is currently used for the "Edit" side of https://www.openstreetmap.org - i.e. when you are in edit mode there and add a new node, on the left sidebar you get asked what type of feature is this. That sidebar has a search that matches human words to OSM data types. This would initially suffice and any improvements to that could also be upstreamed to the aforementioned website. It would be convenient if that could fit a button and feature for any user feedback for missing or unmatched strings - something that should be found but isn't yet. That would then cover regional variations of the English vocabulary as well.

UI-wise there are many options where to put that and I am not very proficient in figuring this out. The end result of this UI interaction would be a way to get the desired type of node/feature displayed on the map in the same way as when the user currently clicks on the <kbd>Restaurant</kbd> button or after searching for and navigating to `London` types `fire statio` (without the last letter) into Qwant search.
1. It could be a search syntax - e.g. `nearby:` prefix. Thus typing `nearby: animal` to get suggestions `nearby: veterinary clinic` and `nearby: zoo` in the search drop down and then clicking on them. I think this solution has the disadvantage of terrible discoverability. The advantage is that this could take tag-and-key pairs from power users to search for anything that exists in OSM data - not only the ones that have human word matches (I think I've had a few types missing from Id editor during my OSM edit career).

![image](https://user-images.githubusercontent.com/9165395/116122708-ceea5380-a6ca-11eb-92fc-a73260c955dc.png)

2. A button in the <kbd>See more services nearby</kbd> menu for <kbd>Custom</kbd> or <kbd>More</kbd> or <kbd>Other</kbd>. Also quite hard to notice. But mostly you need it when you are intently browsing that menu anyway.

![image](https://user-images.githubusercontent.com/9165395/116120903-ba0cc080-a6c8-11eb-9df0-273c013dd5f4.png)

3. Similar to the above one, but instead of a button that looks like others, another search bar.

![image](https://user-images.githubusercontent.com/9165395/116120560-5387a280-a6c8-11eb-976e-425ed7e4c999.png)

4. Similar to the above one, but instead of a new search bar, the existing one gets replaced with another in a way that is very clear to the user. (My mockup is ugly.)

![image](https://user-images.githubusercontent.com/9165395/116123743-0e656f80-a6cc-11eb-9597-d2e11d6316bf.png)

**Comment by Charlotte-Ziegler** [comment]
This issue has been resolved :-) Now you can search by type.

**Comment by i-need-to-tell-you-something** [comment]
Searching for "ATM" gives banks instead.
Still no way to search for any of the above:

    emergency=defibrillator
    amenity=fire_station
    amenity=food_sharing
    leisure=playground
    amenity=bicycle_parking
    amenity=drinking_water
    amenity=post_box
